### ISSUE TITLE
Training on a Titan XP or any other GPU with 12GB memory

### ISSUE THREAD

**Issue by prabh27** [allenai/SciREX#21]
Hi, 

Thanks for providing the code and clear instructions on how to reproduce the results. 

I am trying to train the base model using Titan XP GPUs, however, I am running out of memory issues. I see that in the original setup, you used 48GB Quadra RTX 8000 GPUs. Titan XP only has 12GB of memory. 

Can I modify the code somehow to get a time/space tradeoff and be able to use a lower memory GPU?

**Comment by successar** [comment]
You may be able to get it to work by changing the batch size here https://github.com/allenai/SciREX/blob/7daad660fe94f504433590b7a781cfabe1e179c6/scirex/training_config/template_full.libsonnet#L98 . Since we are passing in the whole document at a time, we used larger GPU. This allows us to get relations between entities that separated by a long distance. Changing the batch size will change the results.

**Comment by successar** [comment]
Please reopen the issue if reducing batch size doesn't work for you.

**Comment by prabh27** [comment]
It works, thanks
